### PR TITLE
Add favicon and fix #197

### LINKED ISSUE #197: Invalid characters in directory name : <->-vs-react-fragment
The directory **/client/posts/<->-vs-react-fragment** is causing git clone to fail as < and > are considered to be invalid in directory names.

So I suggest renaming it into something like `react-fragment-shorthand-vs-longhand` or `rf-shorthand-vs-rf-longhand`.

### PR DESCRIPTION
**Pull request by monkeyscript**
Added a favicon for the site.

Instagram Post - 1

And fixed #197. I had to rename the directory anyway to run this project.

### CODE REVIEW

**Comment by phuoc-ng** [comment]
Amazing ❤️ 
Can you rename the folder to `react-fragment-shorthand-vs-react-fragment-longhand`?

**Comment by monkeyscript** [comment]
Updated @phuoc-ng

**Comment by phuoc-ng** [comment]
@monkeyscript May I ask for the original logo file (png), so I can use it on other places?
I'll add a credit in the footer of website.

**Comment by monkeyscript** [comment]
That's the one I uploaded earlier in this PR.

**Comment by phuoc-ng** [comment]
The live site https://thisthat.dev is updated 🎉

**Comment by monkeyscript** [comment]
Here's a link if you want SVG or JPG or even larger PNG.

https://www.figma.com/file/i2OoA5fF2t7M8x3TQ4MNDk/Untitled?node-id=0%3A1

**Comment by phuoc-ng** [comment]
Thanks you https://twitter.com/nghuuphuoc/status/1313836779133374464 ❤️

**Pull request merged**
